[hooks]
pre-commit = "cargo check --locked && cargo clippy --locked -- -D warnings && cargo fmt --all -- --check && cargo test --locked"
prepare-commit-msg = "exec < /dev/tty && koji --hook -a || true"

[logging]
verbose = true
